spring.application.name=contas-api

spring.datasource.url=jdbc:postgresql://localhost:5432/contas_db
spring.datasource.username=postgres
spring.datasource.password=150998

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true